### PR TITLE
Re-organize and update

### PR DESCRIPTION
**Pull request by garikbesson**
update dependencies, code structure, tests, README

### CODE REVIEW

**Comment by gagdiez** [comment]
@denbite, please take a look

**Comment by denbite** [comment]
I've written up more unit tests for better coverage, it's been increased from 69% to 96%
The remaining 4% belong to the `ft_resolve_transfer` function, which can't be tested properly with unit testing

**Before**
telegram-cloud-photo-size-2-5386478980707772720-y

**After**
telegram-cloud-photo-size-2-5386478980707772727-y

**Comment by garikbesson** [comment]
> I've written up more unit tests for better coverage, it's been increased from 69% to 96% The remaining 4% belong to the `ft_resolve_transfer` function, which can't be tested properly with unit testing
> 
> **Before** telegram-cloud-photo-size-2-5386478980707772720-y
> 
> **After** telegram-cloud-photo-size-2-5386478980707772727-y

What is that tool on your screens?

**Comment by denbite** [comment]
* restructured integration tests to make them as deterministic as possible
* improved readability of `tests` folder
* compiled DeFi contract so we don't have to do it for each test case
* introduced lazy compilation of Fungible Token inside tests to prevent the same contract from being built many times

**Review by gagdiez — APPROVED** [review]

**Pull request merged**
